application: is429gaetest
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /api/.*
  script: app.application

- url: /css/(.*\.css)
  mime_type: text/css
  static_files: public/css/\1
  upload: public/css/(.*\.css)

- url: /js/(.*\.js)
  mime_type: text/javascript
  static_files: public/js/\1
  upload: public/js/(.*\.js)

- url: /pages/(.*\.html)
  mime_type: text/html
  static_files: public/pages/\1
  upload: public/pages/(.*\.html)

libraries:
- name: PIL
  version: latest